### ISSUE TITLE
Error with 2.9

### ISSUE THREAD

**Issue by Beliar-666** [Eisbaeeer/CO2light#5]
Hello,
i just updated to 2.9 and now i got on the startpage:
`null
null
null
192.168.178.xxx`

Also on page Humidity, Temp, and pressure i got first line null and other Line the measured data. Only on pge CO2 there is CO2 and the Data.

Running on Nodemcu v2

**Comment by Eisbaeeer** [comment]
Hello Beliar
In new version you can use different languages. Please upload the language file to the CO2light via webbrowser. I updated the README.md to get running:  https://github.com/Eisbaeeer/CO2light#language-support
Cheers
